Okulbilisim\MessageBundle\Entity\Thread:
    type: entity
    table: cc_message_thread
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        messages:
            targetEntity: Okulbilisim\MessageBundle\Entity\Message
            mappedBy: thread
        envelopes:
            targetEntity: Okulbilisim\MessageBundle\Entity\Envelope
            mappedBy: thread
