messages_bundle_licence:
    pattern:  /{_locale}/messages/licence
    defaults: { _controller: OjsMessageMessageBundle:CustomPages:showLicence, _locale: en }
    
OjsMessageMessageBundle-User-Folder:
    resource: "@OjsMessageMessageBundle/Resources/config/routing/user-folder.yml"
    prefix: /{_locale}/messages

OjsMessageMessageBundle-User-Message:
    resource: "@OjsMessageMessageBundle/Resources/config/routing/user-message.yml"
    prefix: /{_locale}/messages
