OkulbilisimMessageBundle-User-Folder:
    resource: "@OkulbilisimMessageBundle/Resources/config/routing/user-folder.yml"
    prefix: /messages

OkulbilisimMessageBundle-User-Message:
    resource: "@OkulbilisimMessageBundle/Resources/config/routing/user-message.yml"
    prefix: /messages
