#namespaces:
#    OjsMessageMessageBundle: OjsMessage\MessageBundle\Form\Validator\Constraints\
#

#%ojs_message_message.entity.message.class%:
OjsMessage\MessageBundle\Entity\Message:
    properties:
        sendTo:
            - Type: { type: string, groups: [message_send] }
            - NotBlank: { groups: [message_send] }
            - Length: { max: 255, groups: [message_send] }
            - OjsMessage\MessageBundle\Form\Validator\Constraints\SendTo: {  groups: [message_send] }
        subject:
            - Type: { type: string, groups: [message_send] }
            - NotBlank: { groups: [message_send] }
            - Length: { min: 5, max: 255, groups: [message_send] }
        body:
            - Type: { type: string, groups: [message_send] }
            - NotBlank: { groups: [message_send] }
            - Length: { min: 5, max: 5000, groups: [message_send] }
        #isFlagged:
        #    - Type: bool
