parameters:

    # Service Parameters defined in app/config.
    okulbilisim_message.component.server.message.class: Okulbilisim\MessageBundle\Component\Server\MessageServer
    okulbilisim_message.component.helper.pagination_config.class: Okulbilisim\MessageBundle\Component\Helper\PaginationConfigHelper
    okulbilisim_message.component.crumb_builder.class: Okulbilisim\MessageBundle\Component\Crumbs\CrumbBuilder
    okulbilisim_message.component.crumb_factory.class: Okulbilisim\MessageBundle\Component\Crumbs\Factory\CrumbFactory
    okulbilisim_message.component.helper.folder.class: Okulbilisim\MessageBundle\Component\Helper\FolderHelper
    okulbilisim_message.component.helper.quota.class:  Okulbilisim\MessageBundle\Component\Helper\QuotaHelper
    okulbilisim_message.component.event_listener.flash.class: Okulbilisim\MessageBundle\Component\Dispatcher\Listener\FlashListener
    okulbilisim_message.component.event_listener.stats.class: Okulbilisim\MessageBundle\Component\Dispatcher\Listener\StatListener

services:

    okulbilisim_message.component.server.message:
        class: %okulbilisim_message.component.server.message.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.model.folder
            - @okulbilisim_message.model.message
            - @okulbilisim_message.model.envelope
            - @okulbilisim_message.model.user
            - @okulbilisim_message.component.helper.quota
            - @okulbilisim_message.component.helper.folder

    okulbilisim_message.component.helper.folder:
        class: %okulbilisim_message.component.helper.folder.class%
        arguments:
            - @okulbilisim_message.model.folder

    okulbilisim_message.component.helper.quota:
        class: %okulbilisim_message.component.helper.quota.class%
        arguments:
            - %okulbilisim_message.quotas.max_messages%

    okulbilisim_message.component.helper.pagination_config:
        class: %okulbilisim_message.component.helper.pagination_config.class%
        arguments:
            - %okulbilisim_message.folder.show.messages_per_page%

    #
    # Dashboard Integrator.
    #
    okulbilisim_message.component.dashboard.integrator:
        class: %okulbilisim_message.component.dashboard.integrator.class%
        tags:
            - { name: ojs_component_dashboard.integrator }

    okulbilisim_message.component.flood_control:
        class: %okulbilisim_message.component.flood_control.class%
        arguments:
            - @security.context
            - @session
            - %kernel.environment%
            - %okulbilisim_message.message.flood_control.send_limit%
            - %okulbilisim_message.message.flood_control.block_for_minutes%

    #
    # Event Subscribers.
    #
    okulbilisim_message.component.event_listener.flash:
        class: %okulbilisim_message.component.event_listener.flash.class%
        arguments: [@session]
        tags:
            - { name: kernel.event_subscriber }

    okulbilisim_message.component.event_listener.stats:
        class: %okulbilisim_message.component.event_listener.stats.class%
        arguments:
            - @okulbilisim_message.model.folder
            - @okulbilisim_message.model.envelope
            - @okulbilisim_message.model.registry
        tags:
            - { name: kernel.event_subscriber }

    #
    # Crumbs.
    #
    okulbilisim_message.component.crumb_factory:
        class: %okulbilisim_message.component.crumb_factory.class%
        arguments:
            - @translator
            - @router

    okulbilisim_message.component.crumb_builder:
        class: %okulbilisim_message.component.crumb_builder.class%
        arguments:
            - @okulbilisim_message.component.crumb_factory
