parameters:

    # Service Parameters defined in app/config

services:

    #
    # Message Forms.
    #
    ojs_message_message.form.type.message:
        class: %ojs_message_message.form.type.message.class%
        arguments:
            - %ojs_message_message.entity.message.class%

    ojs_message_message.form.handler.message:
        class: %ojs_message_message.form.handler.message.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @ojs_message_message.form.type.message
            - @ojs_message_message.model.message
            - @ojs_message_message.component.flood_control
            - @ojs_message_message.component.server.message

    ojs_message_message.form.handler.message_reply:
        class: %ojs_message_message.form.handler.message_reply.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @ojs_message_message.form.type.message
            - @ojs_message_message.model.message
            - @ojs_message_message.component.flood_control
            - @ojs_message_message.component.server.message

    ojs_message_message.form.handler.message_forward:
        class: %ojs_message_message.form.handler.message_forward.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @ojs_message_message.form.type.message
            - @ojs_message_message.model.message
            - @ojs_message_message.component.flood_control
            - @ojs_message_message.component.server.message

    ojs_message_message.form.validator.send_to:
        class: %ojs_message_message.form.validator.send_to.class%
        arguments:
            - @ojs_message_message.model.user
        tags:
            - { name: validator.constraint_validator, alias: SendToValidator }
