parameters:

    # Service Parameters defined in app/config

services:

    #
    # Managers.
    #

    ojstr_message_message.manager.folder:
        class: %ojstr_message_message.manager.folder.class%
        arguments:
            - @event_dispatcher
            - @ojstr_message_message.gateway.folder

    ojstr_message_message.manager.envelope:
        class: %ojstr_message_message.manager.envelope.class%
        arguments:
            - @event_dispatcher
            - @ojstr_message_message.gateway.envelope

    ojstr_message_message.manager.message:
        class: %ojstr_message_message.manager.message.class%
        arguments:
            - @event_dispatcher
            - @ojstr_message_message.gateway.message

    ojstr_message_message.manager.thread:
        class: %ojstr_message_message.manager.thread.class%
        arguments:
            - @event_dispatcher
            - @ojstr_message_message.gateway.thread

    ojstr_message_message.manager.registry:
        class: %ojstr_message_message.manager.registry.class%
        arguments:
            - @event_dispatcher
            - @ojstr_message_message.gateway.registry

    ojstr_message_message.manager.user:
        class: %ojstr_message_message.manager.user.class%
        arguments:
            - @event_dispatcher
            - @ojstr_message_message.gateway.user
