parameters:

    # Service Parameters defined in app/config

services:

    #
    # Gateways.
    #

    okulbilisim_message.gateway.folder:
        class: %okulbilisim_message.gateway.folder.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %okulbilisim_message.entity.folder.class%
            - @knp_paginator
            - %okulbilisim_message.template.pager_theme%

    okulbilisim_message.gateway.envelope:
        class: %okulbilisim_message.gateway.envelope.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %okulbilisim_message.entity.envelope.class%
            - @knp_paginator
            - %okulbilisim_message.template.pager_theme%

    okulbilisim_message.gateway.message:
        class: %okulbilisim_message.gateway.message.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %okulbilisim_message.entity.message.class%
            - @knp_paginator
            - %okulbilisim_message.template.pager_theme%

    okulbilisim_message.gateway.thread:
        class: %okulbilisim_message.gateway.thread.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %okulbilisim_message.entity.thread.class%
            - @knp_paginator
            - %okulbilisim_message.template.pager_theme%

    okulbilisim_message.gateway.registry:
        class: %okulbilisim_message.gateway.registry.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %okulbilisim_message.entity.registry.class%
            - @knp_paginator
            - %okulbilisim_message.template.pager_theme%

    okulbilisim_message.gateway.user:
        class: %okulbilisim_message.gateway.user.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %okulbilisim_message.entity.user.class%
            - @knp_paginator
            - %okulbilisim_message.template.pager_theme%
