parameters:

    # Service Parameters defined in app/config

services:

    #
    # Managers.
    #

    ojs_message_message.manager.folder:
        class: %ojs_message_message.manager.folder.class%
        arguments:
            - @event_dispatcher
            - @ojs_message_message.gateway.folder

    ojs_message_message.manager.envelope:
        class: %ojs_message_message.manager.envelope.class%
        arguments:
            - @event_dispatcher
            - @ojs_message_message.gateway.envelope

    ojs_message_message.manager.message:
        class: %ojs_message_message.manager.message.class%
        arguments:
            - @event_dispatcher
            - @ojs_message_message.gateway.message

    ojs_message_message.manager.thread:
        class: %ojs_message_message.manager.thread.class%
        arguments:
            - @event_dispatcher
            - @ojs_message_message.gateway.thread

    ojs_message_message.manager.registry:
        class: %ojs_message_message.manager.registry.class%
        arguments:
            - @event_dispatcher
            - @ojs_message_message.gateway.registry

    ojs_message_message.manager.user:
        class: %ojs_message_message.manager.user.class%
        arguments:
            - @event_dispatcher
            - @ojs_message_message.gateway.user
