parameters:

    # Service Parameters defined in app/config

services:

    #
    # Managers.
    #

    okulbilisim_message.manager.folder:
        class: %okulbilisim_message.manager.folder.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.gateway.folder

    okulbilisim_message.manager.envelope:
        class: %okulbilisim_message.manager.envelope.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.gateway.envelope

    okulbilisim_message.manager.message:
        class: %okulbilisim_message.manager.message.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.gateway.message

    okulbilisim_message.manager.thread:
        class: %okulbilisim_message.manager.thread.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.gateway.thread

    okulbilisim_message.manager.registry:
        class: %okulbilisim_message.manager.registry.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.gateway.registry

    okulbilisim_message.manager.user:
        class: %okulbilisim_message.manager.user.class%
        arguments:
            - @event_dispatcher
            - @okulbilisim_message.gateway.user
