parameters:

    # Service Parameters defined in app/config

services:

    #
    # Repositories.
    #

    okulbilisim_message.repository.folder:
        class: %okulbilisim_message.repository.folder.class%
        arguments:
            - @okulbilisim_message.gateway.folder

    okulbilisim_message.repository.envelope:
        class: %okulbilisim_message.repository.envelope.class%
        arguments:
            - @okulbilisim_message.gateway.envelope

    okulbilisim_message.repository.message:
        class: %okulbilisim_message.repository.message.class%
        arguments:
            - @okulbilisim_message.gateway.message

    okulbilisim_message.repository.thread:
        class: %okulbilisim_message.repository.thread.class%
        arguments:
            - @okulbilisim_message.gateway.thread

    okulbilisim_message.repository.registry:
        class: %okulbilisim_message.repository.registry.class%
        arguments:
            - @okulbilisim_message.gateway.registry

    okulbilisim_message.repository.user:
        class: %okulbilisim_message.repository.user.class%
        arguments:
            - @okulbilisim_message.gateway.user
