parameters:

    # Service Parameters defined in app/config

services:

    #
    # Twig Extensions.
    #
    okulbilisim_message.component.twig_extension.registry:
        class: %okulbilisim_message.component.twig_extension.registry.class%
        arguments:
            - @okulbilisim_message.model.registry
            - @security.context
        tags:
            - { name: twig.extension }

    okulbilisim_message.component.twig_extension.folder_list:
        class: %okulbilisim_message.component.twig_extension.folder_list.class%
        arguments:
            - @okulbilisim_message.component.helper.folder
            - @security.context
        tags:
            - { name: twig.extension }
