okulbilisim_message_user_mail_show_by_id:
    path:  /{envelopeId}/show
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:showMessage, _locale: en }

okulbilisim_message_user_mail_compose:
    path:  /compose
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:compose, _locale: en, userId: null }

okulbilisim_message_user_mail_compose_to:
    path:  /compose-to/{userId}
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:compose, _locale: en, userId: null }

okulbilisim_message_user_mail_compose_reply:
    path:  /{envelopeId}/reply
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:reply, _locale: en }

okulbilisim_message_user_mail_compose_forward:
    path:  /{envelopeId}/forward
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:forward, _locale: en }

okulbilisim_message_user_mail_draft_send:
    path:  /{envelopeId}/send
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:sendDraft, _locale: en }

okulbilisim_message_user_mail_mark_as_read:
    path:  /{envelopeId}/mark-as-read
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:markAsRead, _locale: en }

okulbilisim_message_user_mail_mark_as_unread:
    path:  /{envelopeId}/mark-as-unread
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:markAsUnread, _locale: en }

okulbilisim_message_user_mail_delete:
    path:  /{envelopeId}/delete
    defaults: { _controller: OkulbilisimMessageBundle:UserMessage:delete, _locale: en }
