ojs_message_message_user_mail_show_by_id:
    pattern:  /{envelopeId}/show
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:showMessage, _locale: en }

ojs_message_message_user_mail_compose:
    pattern:  /compose
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:compose, _locale: en, userId: null }

ojs_message_message_user_mail_compose_to:
    pattern:  /compose-to/{userId}
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:compose, _locale: en, userId: null }

ojs_message_message_user_mail_compose_reply:
    pattern:  /{envelopeId}/reply
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:reply, _locale: en }

ojs_message_message_user_mail_compose_forward:
    pattern:  /{envelopeId}/forward
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:forward, _locale: en }

ojs_message_message_user_mail_draft_send:
    pattern:  /{envelopeId}/send
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:sendDraft, _locale: en }

ojs_message_message_user_mail_mark_as_read:
    pattern:  /{envelopeId}/mark-as-read
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:markAsRead, _locale: en }

ojs_message_message_user_mail_mark_as_unread:
    pattern:  /{envelopeId}/mark-as-unread
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:markAsUnread, _locale: en }

ojs_message_message_user_mail_delete:
    pattern:  /{envelopeId}/delete
    defaults: { _controller: OjsMessageMessageBundle:UserMessage:delete, _locale: en }
